{
 "title": "Customer Churn Prediction Dashboard",
 "tags": [
  "mlops",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Rate (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[1m])) by (http_status)",
     "legendFormat": "Status {{http_status}}"
    }
   ]
  },
  {
   "title": "API Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(api_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50 Latency"
    }
   ]
  },
  { "title": "Model Prediction Metrics", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Predictions Breakdown (True vs False Churn)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(churn_predictions_total) by (prediction)",
     "legendFormat": "Churn = {{prediction}}"
    }
   ]
  },
  {
   "title": "Prediction Probabilities (Cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(churn_probability_bucket[5m])) by (le)",
     "legendFormat": "Prob <= {{le}}"
    }
   ]
  }
 ]
}